// ABOUTME: Реальные данные товаров, спарсенные с santehnika-online.ru.
// ABOUTME: 35 товаров из 6 категорий раздела «Сантехника».

import type { ParsedProduct } from './types'

export const products: ParsedProduct[] = [
  // === Унитазы (7) ===
  {
    title: 'Унитаз подвесной STWORKI Молде S23401WH безободковый, с микролифтом, антивсплеск',
    slug: 'stworki-molde-s23401wh',
    price: 10990,
    sku: 'S23401WH',
    inStock: 'in_stock',
    rating: { value: 4.8, count: 156 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Длина, см', value: '51.5 см' },
      { key: 'Ширина, см', value: '36 см' },
      { key: 'Высота, см', value: '34 см' },
      { key: 'Направление выпуска', value: 'Горизонтальное (в стену)' },
      { key: 'Вид смывающего потока', value: 'Каскадный слив' },
      { key: 'Сиденье в комплекте', value: 'Да' },
      { key: 'Сиденье с микролифтом', value: 'Да' },
    ],
    categorySlug: 'unitazy',
    imageUrls: [],
  },
  {
    title: 'Унитаз подвесной STWORKI Готланд S13401WH безободковый, с микролифтом, глянцевый белый, антивсплеск',
    slug: 'stworki-gotland-s13401wh',
    price: 13400,
    sku: 'S13401WH',
    inStock: 'in_stock',
    rating: { value: 4.7, count: 89 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Длина, см', value: '53.5 см' },
      { key: 'Ширина, см', value: '36 см' },
      { key: 'Высота, см', value: '36 см' },
      { key: 'Направление выпуска', value: 'Горизонтальное (в стену)' },
      { key: 'Вид смывающего потока', value: 'Каскадный слив' },
      { key: 'Сиденье с микролифтом', value: 'Да' },
      { key: 'Быстросъемное сиденье', value: 'Да' },
    ],
    categorySlug: 'unitazy',
    imageUrls: [],
  },
  {
    title: 'Унитаз-компакт напольный STWORKI Олланд S01400WH с микролифтом, безободковый, белый',
    slug: 'stworki-olland-s01400wh',
    price: 12900,
    sku: 'S01400WH',
    inStock: 'in_stock',
    rating: { value: 4.6, count: 72 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Длина, см', value: '65 см' },
      { key: 'Ширина, см', value: '34 см' },
      { key: 'Высота, см', value: '77 см' },
      { key: 'Направление выпуска', value: 'Горизонтальное (в стену)' },
      { key: 'Вид смывающего потока', value: 'Каскадный слив' },
      { key: 'Кнопка смыва', value: '2 кнопки (эконом)' },
      { key: 'Сиденье с микролифтом', value: 'Да' },
    ],
    categorySlug: 'unitazy',
    imageUrls: [],
  },
  {
    title: 'Унитаз-компакт напольный STWORKI Готланд S13400WH с микролифтом, безободковый, белый',
    slug: 'stworki-gotland-s13400wh',
    price: 15490,
    sku: 'S13400WH',
    inStock: 'in_stock',
    rating: { value: 4.5, count: 45 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Длина, см', value: '62 см' },
      { key: 'Ширина, см', value: '36 см' },
      { key: 'Высота, см', value: '82.5 см' },
      { key: 'Направление выпуска', value: 'Горизонтальное (в стену)' },
      { key: 'Вид смывающего потока', value: 'Каскадный слив' },
      { key: 'Кнопка смыва', value: '2 кнопки (эконом)' },
      { key: 'Сиденье с микролифтом', value: 'Да' },
    ],
    categorySlug: 'unitazy',
    imageUrls: [],
  },
  {
    title: 'Унитаз-компакт напольный STWORKI Вестфолл S08400WH с микролифтом, безободковый, белый',
    slug: 'stworki-vestfoll-s08400wh',
    price: 14990,
    sku: 'S08400WH',
    inStock: 'in_stock',
    rating: { value: 4.6, count: 63 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Длина, см', value: '59 см' },
      { key: 'Ширина, см', value: '39 см' },
      { key: 'Высота, см', value: '80 см' },
      { key: 'Направление выпуска', value: 'Горизонтальное (в стену)' },
      { key: 'Вид смывающего потока', value: 'Смыв торнадо' },
      { key: 'Кнопка смыва', value: '2 кнопки (эконом)' },
      { key: 'Сиденье с микролифтом', value: 'Да' },
    ],
    categorySlug: 'unitazy',
    imageUrls: [],
  },
  {
    title: 'Унитаз подвесной STWORKI Кронборг S28401BK с микролифтом, безободковый, матовый черный',
    slug: 'stworki-kronborg-s28401bk',
    price: 13990,
    sku: 'S28401BK',
    inStock: 'in_stock',
    rating: { value: 4.9, count: 34 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Длина, см', value: '49 см' },
      { key: 'Ширина, см', value: '36 см' },
      { key: 'Высота, см', value: '36 см' },
      { key: 'Направление выпуска', value: 'Горизонтальное (в стену)' },
      { key: 'Вид смывающего потока', value: 'Каскадный слив' },
      { key: 'Сиденье с микролифтом', value: 'Да' },
      { key: 'Быстросъемное сиденье', value: 'Да' },
    ],
    categorySlug: 'unitazy',
    imageUrls: [],
  },
  {
    title: 'Унитаз-компакт напольный DIWO Сочи 0402',
    slug: 'diwo-sochi-0402',
    price: 6490,
    sku: '0402',
    inStock: 'in_stock',
    rating: { value: 4.2, count: 118 },
    specs: [
      { key: 'Бренд', value: 'DIWO (Россия)' },
      { key: 'Длина, см', value: '67 см' },
      { key: 'Ширина, см', value: '36 см' },
      { key: 'Высота, см', value: '74.5 см' },
      { key: 'Направление выпуска', value: 'Горизонтальное (в стену)' },
      { key: 'Вид смывающего потока', value: 'Каскадный слив' },
      { key: 'Кнопка смыва', value: '1 кнопка (полный слив)' },
      { key: 'Система антивсплеск', value: 'Нет' },
    ],
    categorySlug: 'unitazy',
    imageUrls: [],
  },

  // === Раковины (7) ===
  {
    title: 'Накладная раковина STWORKI Молде S23410WH 62 глянцевая белая, прямоугольная',
    slug: 'stworki-molde-s23410wh',
    price: 6210,
    sku: 'S23410WH',
    inStock: 'out_of_stock',
    rating: { value: 4.5, count: 42 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Вид раковины', value: 'Накладная (чаша)' },
      { key: 'Название цвета', value: 'Глянцевый белый' },
      { key: 'Поверхность раковины', value: 'Глянцевая' },
      { key: 'Донный клапан', value: 'Приобретается отдельно' },
      { key: 'Материал', value: 'Фарфор' },
    ],
    categorySlug: 'rakoviny',
    imageUrls: [],
  },
  {
    title: 'Раковина над стиральной машиной STWORKI Авила 60x50 белая, прямоугольная, искусственный камень',
    slug: 'stworki-avila-60x50',
    price: 12125,
    sku: 'AV50',
    inStock: 'out_of_stock',
    rating: { value: 4.3, count: 18 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Вид раковины', value: 'Над стиральной машиной' },
      { key: 'Готовые отверстия под смеситель', value: '1' },
      { key: 'Со скрытым сливом', value: 'Да' },
      { key: 'Материал', value: 'Искусственный камень' },
    ],
    categorySlug: 'rakoviny',
    imageUrls: [],
  },
  {
    title: 'Мебельная раковина DIWO Мурманск A61 накладная, белая, прямоугольная, фаянс',
    slug: 'diwo-murmansk-a61',
    price: 4990,
    sku: 'A61',
    inStock: 'in_stock',
    rating: { value: 4.4, count: 67 },
    specs: [
      { key: 'Бренд', value: 'DIWO (Россия)' },
      { key: 'Готовые отверстия под смеситель', value: '1' },
      { key: 'Поверхность раковины', value: 'Глянцевая' },
      { key: 'Донный клапан', value: 'В комплекте' },
      { key: 'Слив-перелив', value: 'В комплекте' },
      { key: 'Материал', value: 'Фаянс' },
    ],
    categorySlug: 'rakoviny',
    imageUrls: [],
  },
  {
    title: 'Мебельная раковина DIWO Мурманск A71 накладная, белая, прямоугольная, фаянс',
    slug: 'diwo-murmansk-a71',
    price: 6490,
    sku: 'A71',
    inStock: 'in_stock',
    rating: { value: 4.3, count: 53 },
    specs: [
      { key: 'Бренд', value: 'DIWO (Россия)' },
      { key: 'Готовые отверстия под смеситель', value: '1' },
      { key: 'Поверхность раковины', value: 'Глянцевая' },
      { key: 'Донный клапан', value: 'В комплекте' },
      { key: 'Слив-перелив', value: 'В комплекте' },
      { key: 'Материал', value: 'Фаянс' },
    ],
    categorySlug: 'rakoviny',
    imageUrls: [],
  },
  {
    title: 'Накладная раковина STWORKI Берген S21413WH 36 глянцевая белая, круглая',
    slug: 'stworki-bergen-s21413wh',
    price: 4275,
    sku: 'S21413WH',
    inStock: 'in_stock',
    rating: { value: 4.6, count: 31 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Вид раковины', value: 'Накладная (чаша)' },
      { key: 'Название цвета', value: 'Глянцевый белый' },
      { key: 'Поверхность раковины', value: 'Глянцевая' },
      { key: 'Донный клапан', value: 'Приобретается отдельно' },
      { key: 'Материал', value: 'Фарфор' },
    ],
    categorySlug: 'rakoviny',
    imageUrls: [],
  },
  {
    title: 'Накладная раковина STWORKI Ольборг S20410WH 50 глянцевая белая, прямоугольная',
    slug: 'stworki-olborg-s20410wh',
    price: 4950,
    sku: 'S20410WH',
    inStock: 'in_stock',
    rating: { value: 4.5, count: 48 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Вид раковины', value: 'Накладная (чаша)' },
      { key: 'Поверхность раковины', value: 'Глянцевая' },
      { key: 'Донный клапан', value: 'Приобретается отдельно' },
      { key: 'Материал', value: 'Фарфор' },
    ],
    categorySlug: 'rakoviny',
    imageUrls: [],
  },
  {
    title: 'Мебельная раковина DIWO Мурманск A81 накладная, белая, прямоугольная, фаянс',
    slug: 'diwo-murmansk-a81',
    price: 6990,
    sku: 'A81',
    inStock: 'in_stock',
    rating: { value: 4.2, count: 39 },
    specs: [
      { key: 'Бренд', value: 'DIWO (Россия)' },
      { key: 'Готовые отверстия под смеситель', value: '1' },
      { key: 'Поверхность раковины', value: 'Глянцевая' },
      { key: 'Донный клапан', value: 'В комплекте' },
      { key: 'Слив-перелив', value: 'В комплекте' },
      { key: 'Материал', value: 'Фаянс' },
    ],
    categorySlug: 'rakoviny',
    imageUrls: [],
  },

  // === Ванны (7) ===
  {
    title: 'Акриловая ванна DIWO Переславль без опоры 160x70 см, пристенная, белая',
    slug: 'diwo-pereslavl-160x70',
    price: 12900,
    sku: 'Щ0000052109',
    inStock: 'in_stock',
    rating: { value: 4.7, count: 94 },
    specs: [
      { key: 'Бренд', value: 'DIWO (Россия)' },
      { key: 'Объем, л', value: '203 л' },
      { key: 'Толщина листа, см', value: '0.6 см' },
      { key: 'Ориентация', value: 'Универсальная' },
      { key: 'Вид опоры', value: 'Без опоры' },
    ],
    categorySlug: 'vanny',
    imageUrls: [],
  },
  {
    title: 'Акриловая ванна DIWO Анапа без опоры 150x70 см, пристенная, белая',
    slug: 'diwo-anapa-150x70',
    price: 9100,
    sku: 'Щ0000055219',
    inStock: 'in_stock',
    rating: { value: 4.5, count: 112 },
    specs: [
      { key: 'Бренд', value: 'DIWO (Россия)' },
      { key: 'Объем, л', value: '136 л' },
      { key: 'Толщина листа, см', value: '0.3 см' },
      { key: 'Ориентация', value: 'Универсальная' },
      { key: 'Антискользящее покрытие', value: 'Есть' },
      { key: 'Вид опоры', value: 'Без опоры' },
    ],
    categorySlug: 'vanny',
    imageUrls: [],
  },
  {
    title: 'Акриловая ванна DIWO Кострома без опоры 160x70 см, пристенная, белая',
    slug: 'diwo-kostroma-160x70',
    price: 9900,
    sku: 'Щ0000046590',
    inStock: 'out_of_stock',
    rating: { value: 4.4, count: 78 },
    specs: [
      { key: 'Бренд', value: 'DIWO (Россия)' },
      { key: 'Объем, л', value: '184 л' },
      { key: 'Толщина листа, см', value: '0.6 см' },
      { key: 'Ориентация', value: 'Универсальная' },
      { key: 'Вид опоры', value: 'Без опоры' },
    ],
    categorySlug: 'vanny',
    imageUrls: [],
  },
  {
    title: 'Акриловая ванна DIWO Кострома без опоры 170x70 см, пристенная, белая',
    slug: 'diwo-kostroma-170x70',
    price: 9800,
    sku: 'Щ0000046591',
    inStock: 'out_of_stock',
    rating: { value: 4.3, count: 65 },
    specs: [
      { key: 'Бренд', value: 'DIWO (Россия)' },
      { key: 'Объем, л', value: '195 л' },
      { key: 'Толщина листа, см', value: '0.6 см' },
      { key: 'Ориентация', value: 'Универсальная' },
      { key: 'Вид опоры', value: 'Без опоры' },
    ],
    categorySlug: 'vanny',
    imageUrls: [],
  },
  {
    title: 'Акриловая ванна DIWO Анапа без опоры 170x70 см, пристенная, белая',
    slug: 'diwo-anapa-170x70',
    price: 9990,
    sku: 'Щ0000055220',
    inStock: 'in_stock',
    rating: { value: 4.6, count: 87 },
    specs: [
      { key: 'Бренд', value: 'DIWO (Россия)' },
      { key: 'Объем, л', value: '161 л' },
      { key: 'Толщина листа, см', value: '0.3 см' },
      { key: 'Ориентация', value: 'Универсальная' },
      { key: 'Антискользящее покрытие', value: 'Есть' },
      { key: 'Вид опоры', value: 'Без опоры' },
    ],
    categorySlug: 'vanny',
    imageUrls: [],
  },
  {
    title: 'Акриловая ванна DIWO Кострома без опоры 180x70 см, пристенная, белая',
    slug: 'diwo-kostroma-180x70',
    price: 10500,
    sku: 'Щ0000046592',
    inStock: 'out_of_stock',
    rating: { value: 4.4, count: 56 },
    specs: [
      { key: 'Бренд', value: 'DIWO (Россия)' },
      { key: 'Объем, л', value: '209 л' },
      { key: 'Толщина листа, см', value: '0.6 см' },
      { key: 'Ориентация', value: 'Универсальная' },
      { key: 'Вид опоры', value: 'Без опоры' },
    ],
    categorySlug: 'vanny',
    imageUrls: [],
  },
  {
    title: 'Акриловая ванна DIWO Казань без опоры 150x70 см, пристенная, белая',
    slug: 'diwo-kazan-150x70',
    price: 12300,
    sku: 'Щ0000055163',
    inStock: 'in_stock',
    rating: { value: 4.8, count: 103 },
    specs: [
      { key: 'Бренд', value: 'DIWO (Россия)' },
      { key: 'Объем, л', value: '174 л' },
      { key: 'Толщина листа, см', value: '0.4 см' },
      { key: 'Ориентация', value: 'Универсальная' },
      { key: 'Вид опоры', value: 'Без опоры' },
    ],
    categorySlug: 'vanny',
    imageUrls: [],
  },

  // === Смесители (7) ===
  {
    title: 'Душевая стойка STWORKI Лерум S04170CR хром',
    slug: 'stworki-lerum-s04170cr',
    price: 29900,
    sku: 'S04170CR',
    inStock: 'in_stock',
    rating: { value: 4.9, count: 47 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Высота, см', value: '130.3 см' },
      { key: 'Размер верхнего душа, см', value: '25 см' },
      { key: 'Управление', value: 'Термостат' },
      { key: 'Регулировка высоты', value: 'Есть' },
      { key: 'Излив для наполнения ванн', value: 'Есть' },
      { key: 'Верхний душ', value: 'Есть' },
    ],
    categorySlug: 'smesiteli',
    imageUrls: [],
  },
  {
    title: 'Душевая стойка STWORKI Готланд S13170CR хром',
    slug: 'stworki-gotland-s13170cr',
    price: 17990,
    sku: 'S13170CR',
    inStock: 'in_stock',
    rating: { value: 4.7, count: 62 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Высота, см', value: '152.2 см' },
      { key: 'Размер верхнего душа, см', value: '23 см' },
      { key: 'Управление', value: 'Термостат' },
      { key: 'Регулировка высоты', value: 'Есть' },
      { key: 'Излив для наполнения ванн', value: 'Есть' },
      { key: 'Верхний душ', value: 'Есть' },
    ],
    categorySlug: 'smesiteli',
    imageUrls: [],
  },
  {
    title: 'Смеситель для раковины Domaci Равенна D17000CR хром',
    slug: 'domaci-ravenna-d17000cr',
    price: 1490,
    sku: 'D17000CR',
    inStock: 'in_stock',
    rating: { value: 4.1, count: 203 },
    specs: [
      { key: 'Бренд', value: 'Domaci (Россия)' },
      { key: 'Высота излива, см', value: '14.3 см' },
      { key: 'Длина излива, см', value: '12.15 см' },
      { key: 'Материал', value: 'Пластик' },
      { key: 'Механизм', value: 'Керамическая кран-букса' },
      { key: 'Поверхность', value: 'Глянцевая' },
      { key: 'Функция экономии расхода', value: 'Есть' },
    ],
    categorySlug: 'smesiteli',
    imageUrls: [],
  },
  {
    title: 'Смеситель для раковины STWORKI Киркенес S45010S сталь',
    slug: 'stworki-kirkenes-s45010s',
    price: 3490,
    sku: 'S45010S',
    inStock: 'in_stock',
    rating: { value: 4.5, count: 89 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Высота излива, см', value: '6.9 см' },
      { key: 'Длина излива, см', value: '13 см' },
      { key: 'Материал', value: 'Нержавеющая сталь' },
      { key: 'Механизм', value: 'Керамический картридж' },
      { key: 'Поверхность', value: 'Матовая / Брашированная' },
    ],
    categorySlug: 'smesiteli',
    imageUrls: [],
  },
  {
    title: 'Смеситель для раковины STWORKI Эстерсунд S31010BK черный',
    slug: 'stworki-estersund-s31010bk',
    price: 6200,
    sku: 'S31010BK',
    inStock: 'in_stock',
    rating: { value: 4.6, count: 74 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Высота излива, см', value: '8.55 см' },
      { key: 'Длина излива, см', value: '12.55 см' },
      { key: 'Материал', value: 'Латунь' },
      { key: 'Поверхность', value: 'Матовая' },
      { key: 'Функция экономии расхода', value: 'Есть' },
    ],
    categorySlug: 'smesiteli',
    imageUrls: [],
  },
  {
    title: 'Душевая стойка DIWO Орёл DW-ORL75CR хром',
    slug: 'diwo-oryol-dw-orl75cr',
    price: 5990,
    sku: 'DW-ORL75CR',
    inStock: 'in_stock',
    rating: { value: 4.3, count: 56 },
    specs: [
      { key: 'Бренд', value: 'DIWO (Россия)' },
      { key: 'Высота, см', value: '148.4 см' },
      { key: 'Размер верхнего душа, см', value: '22.5 см' },
      { key: 'Регулировка высоты', value: 'Есть' },
      { key: 'Излив для наполнения ванн', value: 'Есть' },
      { key: 'Верхний душ', value: 'Есть' },
      { key: 'Материал', value: 'Нержавеющая сталь / Пластик' },
    ],
    categorySlug: 'smesiteli',
    imageUrls: [],
  },
  {
    title: 'Смеситель с длинным изливом для ванны STWORKI Киркенес S45115S сталь',
    slug: 'stworki-kirkenes-s45115s',
    price: 3990,
    sku: 'S45115S',
    inStock: 'in_stock',
    rating: { value: 4.4, count: 38 },
    specs: [
      { key: 'Бренд', value: 'STWORKI (Россия)' },
      { key: 'Длина излива, см', value: '40 см' },
      { key: 'Материал', value: 'Нержавеющая сталь' },
    ],
    categorySlug: 'smesiteli',
    imageUrls: [],
  },

  // === Полотенцесушители (4) ===
  {
    title: 'Полотенцесушитель водяной Indigo Line LLSHW80-50GDPK3 80x55 см, золото, лесенка, с полкой',
    slug: 'indigo-line-llshw80-50gdpk3',
    price: 25070,
    sku: 'LLSHW80-50GDPK3',
    inStock: 'in_stock',
    rating: { value: 4.7, count: 23 },
    specs: [
      { key: 'Бренд', value: 'Indigo (Россия)' },
      { key: 'Межосевое расстояние, см', value: '50 см' },
      { key: 'Направление подключения', value: 'Нижнее горизонтальное' },
      { key: 'Материал', value: 'Нержавеющая сталь' },
      { key: 'Рабочее давление, бар', value: '8 бар' },
      { key: 'Поверхность', value: 'Глянцевая' },
    ],
    categorySlug: 'polotencesushiteli',
    imageUrls: [],
  },
  {
    title: 'Полотенцесушитель электрический EWRIKA Сафо D 65x55 см, подключение слева, матовый черный, лесенка',
    slug: 'ewrika-safo-d-65x55',
    price: 11840,
    sku: '4627201609267',
    inStock: 'in_stock',
    rating: { value: 4.4, count: 41 },
    specs: [
      { key: 'Бренд', value: 'EWRIKA (Россия)' },
      { key: 'Монтаж', value: 'Подвесной' },
      { key: 'Материал', value: 'Нержавеющая сталь' },
      { key: 'Теплоноситель', value: 'Антифриз' },
      { key: 'Подключение', value: 'Электропровод с вилкой' },
      { key: 'Мощность, Вт', value: '300 Вт' },
      { key: 'Поверхность', value: 'Матовая' },
    ],
    categorySlug: 'polotencesushiteli',
    imageUrls: [],
  },
  {
    title: 'Полотенцесушитель электрический EWRIKA Кассандра Pd 85x55 см, подключение слева, матовый черный, лесенка',
    slug: 'ewrika-kassandra-pd-85x55',
    price: 24470,
    sku: '4656759179755',
    inStock: 'in_stock',
    rating: { value: 4.6, count: 19 },
    specs: [
      { key: 'Бренд', value: 'EWRIKA (Россия)' },
      { key: 'Монтаж', value: 'Подвесной' },
      { key: 'Материал', value: 'Нержавеющая сталь' },
      { key: 'Теплоноситель', value: 'Антифриз' },
      { key: 'Направление подключения', value: 'Левое' },
      { key: 'Мощность, Вт', value: '300 Вт' },
      { key: 'Поверхность', value: 'Матовая' },
    ],
    categorySlug: 'polotencesushiteli',
    imageUrls: [],
  },
  {
    title: 'Полотенцесушитель электрический Boheme Uno 726-MG 150x10 см, скрытое подключение, matt gold, I-образный',
    slug: 'boheme-uno-726-mg',
    price: 34860,
    sku: '726-MG',
    inStock: 'in_stock',
    rating: { value: 4.8, count: 12 },
    specs: [
      { key: 'Бренд', value: 'Boheme (Италия)' },
      { key: 'Монтаж', value: 'Подвесной' },
      { key: 'Материал', value: 'Сталь' },
      { key: 'Теплоноситель', value: 'Сухой' },
      { key: 'Подключение', value: 'Скрытое электрическое соединение' },
      { key: 'Мощность, Вт', value: '150 Вт' },
      { key: 'Поверхность', value: 'Матовая' },
    ],
    categorySlug: 'polotencesushiteli',
    imageUrls: [],
  },

  // === Биде (3) ===
  {
    title: 'Биде подвесное SantiLine SL-5058 глянцевое белое',
    slug: 'santiline-sl-5058',
    price: 13780,
    sku: 'SL-5058',
    inStock: 'in_stock',
    rating: { value: 4.3, count: 27 },
    specs: [
      { key: 'Бренд', value: 'SantiLine (Россия)' },
      { key: 'Диаметр слива биде, см', value: '4,5 см' },
      { key: 'Материал', value: 'Фаянс' },
      { key: 'Поверхность', value: 'Глянцевая' },
      { key: 'Антигрязевое покрытие', value: 'Есть' },
      { key: 'Слив-перелив', value: 'Встроенный, в комплекте' },
    ],
    categorySlug: 'bide',
    imageUrls: [],
  },
  {
    title: 'Биде напольное Jacob Delafon Rodin+ EBJ0002-00 глянцевое белое',
    slug: 'jacob-delafon-rodin-ebj0002',
    price: 37440,
    sku: 'EBJ0002-00',
    inStock: 'in_stock',
    rating: { value: 4.7, count: 15 },
    specs: [
      { key: 'Бренд', value: 'Jacob Delafon (Франция)' },
      { key: 'Диаметр слива биде, см', value: '4,5 см' },
      { key: 'Материал', value: 'Фарфор' },
      { key: 'Поверхность', value: 'Глянцевая' },
      { key: 'Слив-перелив', value: 'Встроенный, в комплекте' },
    ],
    categorySlug: 'bide',
    imageUrls: [],
  },
  {
    title: 'Биде подвесное BOND Oval F01-20 глянцевое белое',
    slug: 'bond-oval-f01-20',
    price: 14980,
    sku: 'F01-20',
    inStock: 'in_stock',
    rating: { value: 4.5, count: 22 },
    specs: [
      { key: 'Бренд', value: 'BOND (Россия)' },
      { key: 'Диаметр слива биде, см', value: '4,5 см' },
      { key: 'Материал', value: 'Фарфор' },
      { key: 'Поверхность', value: 'Глянцевая' },
      { key: 'Антибактериальное покрытие', value: 'Есть' },
      { key: 'Антигрязевое покрытие', value: 'Есть' },
      { key: 'Слив-перелив', value: 'Встроенный, в комплекте' },
    ],
    categorySlug: 'bide',
    imageUrls: [],
  },
]
