// ABOUTME: Реалистичные данные товаров для каталога сантехники.
// ABOUTME: По 3-6 товаров на корневую категорию, основано на ассортименте santehnika-online.ru.

import type { ParsedProduct } from './types'

const r = (min: number, max: number) => +(Math.random() * (max - min) + min).toFixed(1)
const ri = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min

export const products: ParsedProduct[] = [
  // Унитазы
  {
    title: 'Унитаз напольный Roca The Gap 342477000',
    slug: 'roca-the-gap-342477000',
    price: 14500,
    sku: 'ROCA-342477000',
    inStock: 'in_stock',
    rating: { value: r(4.2, 4.9), count: ri(15, 120) },
    specs: [
      { key: 'Бренд', value: 'Roca' },
      { key: 'Тип', value: 'Напольный' },
      { key: 'Материал', value: 'Санфаянс' },
      { key: 'Цвет', value: 'Белый' },
      { key: 'Высота, мм', value: '400' },
      { key: 'Ширина, мм', value: '365' },
      { key: 'Страна', value: 'Испания' },
    ],
    categorySlug: 'unitazy',
    imageUrls: [],
  },
  {
    title: 'Унитаз подвесной Villeroy & Boch Subway 2.0',
    slug: 'villeroy-boch-subway-2-0',
    price: 28900,
    sku: 'VB-5614R001',
    inStock: 'in_stock',
    rating: { value: r(4.5, 5.0), count: ri(30, 200) },
    specs: [
      { key: 'Бренд', value: 'Villeroy & Boch' },
      { key: 'Тип', value: 'Подвесной' },
      { key: 'Материал', value: 'Фарфор' },
      { key: 'Цвет', value: 'Белый альпин' },
      { key: 'Длина, мм', value: '560' },
      { key: 'Покрытие', value: 'CeramicPlus' },
      { key: 'Страна', value: 'Германия' },
    ],
    categorySlug: 'unitazy',
    imageUrls: [],
  },
  {
    title: 'Унитаз-компакт Cersanit Carina New Clean On',
    slug: 'cersanit-carina-new-clean-on',
    price: 9200,
    sku: 'CERS-S-KO-CAR-COn-3/5-DL',
    inStock: 'in_stock',
    rating: { value: r(4.0, 4.7), count: ri(50, 300) },
    specs: [
      { key: 'Бренд', value: 'Cersanit' },
      { key: 'Тип', value: 'Компакт' },
      { key: 'Смыв', value: 'Безободковый' },
      { key: 'Цвет', value: 'Белый' },
      { key: 'Объём бачка, л', value: '3/5' },
      { key: 'Страна', value: 'Польша' },
    ],
    categorySlug: 'unitazy',
    imageUrls: [],
  },
  {
    title: 'Инсталляция Geberit Duofix 111.300.00.5',
    slug: 'geberit-duofix-111-300',
    price: 22400,
    sku: 'GEB-111300005',
    inStock: 'in_stock',
    rating: { value: r(4.6, 5.0), count: ri(80, 500) },
    specs: [
      { key: 'Бренд', value: 'Geberit' },
      { key: 'Тип', value: 'Рамная инсталляция' },
      { key: 'Высота, мм', value: '1120' },
      { key: 'Ширина, мм', value: '500' },
      { key: 'Глубина, мм', value: '120' },
      { key: 'Страна', value: 'Швейцария' },
    ],
    categorySlug: 'unitazy',
    imageUrls: [],
  },
  {
    title: 'Унитаз напольный Laufen Pro S 8.2096.1',
    slug: 'laufen-pro-s-82096',
    price: 18700,
    sku: 'LAU-820961',
    inStock: 'preorder',
    rating: { value: r(4.3, 4.8), count: ri(10, 60) },
    specs: [
      { key: 'Бренд', value: 'Laufen' },
      { key: 'Тип', value: 'Напольный' },
      { key: 'Материал', value: 'Фарфор' },
      { key: 'Цвет', value: 'Белый' },
      { key: 'Страна', value: 'Швейцария' },
    ],
    categorySlug: 'unitazy',
    imageUrls: [],
  },

  // Раковины
  {
    title: 'Раковина накладная Duravit D-Neo 2372600070',
    slug: 'duravit-d-neo-2372600070',
    price: 16800,
    sku: 'DUR-2372600070',
    inStock: 'in_stock',
    rating: { value: r(4.4, 4.9), count: ri(20, 100) },
    specs: [
      { key: 'Бренд', value: 'Duravit' },
      { key: 'Тип', value: 'Накладная' },
      { key: 'Форма', value: 'Прямоугольная' },
      { key: 'Ширина, мм', value: '600' },
      { key: 'Глубина, мм', value: '440' },
      { key: 'Материал', value: 'Керамика' },
      { key: 'Страна', value: 'Германия' },
    ],
    categorySlug: 'rakoviny',
    imageUrls: [],
  },
  {
    title: 'Раковина подвесная Roca Debba 327600000',
    slug: 'roca-debba-327600000',
    price: 5400,
    sku: 'ROCA-327600000',
    inStock: 'in_stock',
    rating: { value: r(4.1, 4.6), count: ri(40, 200) },
    specs: [
      { key: 'Бренд', value: 'Roca' },
      { key: 'Тип', value: 'Подвесная' },
      { key: 'Форма', value: 'Прямоугольная' },
      { key: 'Ширина, мм', value: '600' },
      { key: 'Отверстие под смеситель', value: 'Да' },
      { key: 'Страна', value: 'Испания' },
    ],
    categorySlug: 'rakoviny',
    imageUrls: [],
  },
  {
    title: 'Раковина на пьедестале Ideal Standard Tempo T0567',
    slug: 'ideal-standard-tempo-t0567',
    price: 7900,
    sku: 'IS-T056701',
    inStock: 'in_stock',
    rating: { value: r(4.0, 4.5), count: ri(15, 80) },
    specs: [
      { key: 'Бренд', value: 'Ideal Standard' },
      { key: 'Тип', value: 'На пьедестале' },
      { key: 'Ширина, мм', value: '550' },
      { key: 'Материал', value: 'Фарфор' },
      { key: 'Цвет', value: 'Белый' },
      { key: 'Страна', value: 'Бельгия' },
    ],
    categorySlug: 'rakoviny',
    imageUrls: [],
  },
  {
    title: 'Раковина врезная Jacob Delafon Odeon Up E4736',
    slug: 'jacob-delafon-odeon-up-e4736',
    price: 12300,
    sku: 'JD-E473600',
    inStock: 'preorder',
    rating: { value: r(4.3, 4.8), count: ri(10, 50) },
    specs: [
      { key: 'Бренд', value: 'Jacob Delafon' },
      { key: 'Тип', value: 'Врезная' },
      { key: 'Форма', value: 'Овальная' },
      { key: 'Ширина, мм', value: '560' },
      { key: 'Страна', value: 'Франция' },
    ],
    categorySlug: 'rakoviny',
    imageUrls: [],
  },

  // Ванны
  {
    title: 'Ванна акриловая Ravak Formy 01 170x75',
    slug: 'ravak-formy-01-170x75',
    price: 34500,
    sku: 'RAV-C691000000',
    inStock: 'in_stock',
    rating: { value: r(4.5, 5.0), count: ri(20, 120) },
    specs: [
      { key: 'Бренд', value: 'Ravak' },
      { key: 'Материал', value: 'Акрил' },
      { key: 'Длина, мм', value: '1700' },
      { key: 'Ширина, мм', value: '750' },
      { key: 'Глубина, мм', value: '440' },
      { key: 'Объём, л', value: '220' },
      { key: 'Страна', value: 'Чехия' },
    ],
    categorySlug: 'vanny',
    imageUrls: [],
  },
  {
    title: 'Ванна чугунная Roca Continental 150x70',
    slug: 'roca-continental-150x70',
    price: 27800,
    sku: 'ROCA-21291100R',
    inStock: 'in_stock',
    rating: { value: r(4.6, 5.0), count: ri(100, 500) },
    specs: [
      { key: 'Бренд', value: 'Roca' },
      { key: 'Материал', value: 'Чугун' },
      { key: 'Длина, мм', value: '1500' },
      { key: 'Ширина, мм', value: '700' },
      { key: 'Глубина, мм', value: '420' },
      { key: 'Вес, кг', value: '73' },
      { key: 'Страна', value: 'Испания' },
    ],
    categorySlug: 'vanny',
    imageUrls: [],
  },
  {
    title: 'Ванна стальная Kaldewei Saniform Plus 373-1',
    slug: 'kaldewei-saniform-plus-373',
    price: 19500,
    sku: 'KAL-112630003001',
    inStock: 'in_stock',
    rating: { value: r(4.3, 4.8), count: ri(30, 150) },
    specs: [
      { key: 'Бренд', value: 'Kaldewei' },
      { key: 'Материал', value: 'Сталь' },
      { key: 'Длина, мм', value: '1700' },
      { key: 'Ширина, мм', value: '750' },
      { key: 'Эмаль', value: 'Kaldewei Easy-Clean' },
      { key: 'Страна', value: 'Германия' },
    ],
    categorySlug: 'vanny',
    imageUrls: [],
  },
  {
    title: 'Ванна отдельностоящая BelBagno BB42-1700',
    slug: 'belbagno-bb42-1700',
    price: 89000,
    sku: 'BB-421700',
    inStock: 'preorder',
    rating: { value: r(4.7, 5.0), count: ri(5, 30) },
    specs: [
      { key: 'Бренд', value: 'BelBagno' },
      { key: 'Материал', value: 'Акрил' },
      { key: 'Тип', value: 'Отдельностоящая' },
      { key: 'Длина, мм', value: '1700' },
      { key: 'Ширина, мм', value: '800' },
      { key: 'Страна', value: 'Италия' },
    ],
    categorySlug: 'vanny',
    imageUrls: [],
  },

  // Смесители
  {
    title: 'Смеситель для раковины Grohe Eurosmart 23324001',
    slug: 'grohe-eurosmart-23324001',
    price: 7200,
    sku: 'GR-23324001',
    inStock: 'in_stock',
    rating: { value: r(4.4, 4.9), count: ri(60, 400) },
    specs: [
      { key: 'Бренд', value: 'Grohe' },
      { key: 'Тип', value: 'Однорычажный' },
      { key: 'Назначение', value: 'Для раковины' },
      { key: 'Материал', value: 'Латунь' },
      { key: 'Покрытие', value: 'Хром' },
      { key: 'Картридж', value: '35 мм' },
      { key: 'Страна', value: 'Германия' },
    ],
    categorySlug: 'smesiteli',
    imageUrls: [],
  },
  {
    title: 'Смеситель для ванны Hansgrohe Focus E2 31940000',
    slug: 'hansgrohe-focus-e2-31940000',
    price: 11500,
    sku: 'HG-31940000',
    inStock: 'in_stock',
    rating: { value: r(4.5, 5.0), count: ri(40, 250) },
    specs: [
      { key: 'Бренд', value: 'Hansgrohe' },
      { key: 'Тип', value: 'Однорычажный' },
      { key: 'Назначение', value: 'Для ванны' },
      { key: 'Излив', value: 'Фиксированный' },
      { key: 'Покрытие', value: 'Хром' },
      { key: 'Страна', value: 'Германия' },
    ],
    categorySlug: 'smesiteli',
    imageUrls: [],
  },
  {
    title: 'Смеситель для кухни Blanco Mida-S 521454',
    slug: 'blanco-mida-s-521454',
    price: 15800,
    sku: 'BL-521454',
    inStock: 'in_stock',
    rating: { value: r(4.3, 4.8), count: ri(20, 100) },
    specs: [
      { key: 'Бренд', value: 'Blanco' },
      { key: 'Тип', value: 'С выдвижным изливом' },
      { key: 'Назначение', value: 'Для кухни' },
      { key: 'Высота излива, мм', value: '260' },
      { key: 'Покрытие', value: 'Хром' },
      { key: 'Страна', value: 'Германия' },
    ],
    categorySlug: 'smesiteli',
    imageUrls: [],
  },
  {
    title: 'Смеситель для душа Lemark Atlantiss LM3246C',
    slug: 'lemark-atlantiss-lm3246c',
    price: 4900,
    sku: 'LM-3246C',
    inStock: 'in_stock',
    rating: { value: r(4.0, 4.5), count: ri(15, 80) },
    specs: [
      { key: 'Бренд', value: 'Lemark' },
      { key: 'Тип', value: 'Встраиваемый' },
      { key: 'Назначение', value: 'Для душа' },
      { key: 'Покрытие', value: 'Хром' },
      { key: 'Страна', value: 'Чехия' },
    ],
    categorySlug: 'smesiteli',
    imageUrls: [],
  },

  // Душевые кабины
  {
    title: 'Душевой уголок Radaway Essenza New KDJ 90x90',
    slug: 'radaway-essenza-new-kdj-90x90',
    price: 42000,
    sku: 'RAD-385044-01-01',
    inStock: 'in_stock',
    rating: { value: r(4.5, 5.0), count: ri(10, 60) },
    specs: [
      { key: 'Бренд', value: 'Radaway' },
      { key: 'Тип', value: 'Душевой уголок' },
      { key: 'Размер, мм', value: '900x900' },
      { key: 'Высота, мм', value: '2000' },
      { key: 'Стекло', value: 'Прозрачное, 8 мм' },
      { key: 'Страна', value: 'Польша' },
    ],
    categorySlug: 'dushevye-kabiny',
    imageUrls: [],
  },
  {
    title: 'Душевая дверь Cezares Pratico-BF-1 120',
    slug: 'cezares-pratico-bf-1-120',
    price: 28500,
    sku: 'CEZ-PRAT-BF1-120',
    inStock: 'in_stock',
    rating: { value: r(4.2, 4.7), count: ri(8, 40) },
    specs: [
      { key: 'Бренд', value: 'Cezares' },
      { key: 'Тип', value: 'Душевая дверь' },
      { key: 'Ширина, мм', value: '1200' },
      { key: 'Высота, мм', value: '1950' },
      { key: 'Стекло', value: 'Прозрачное, 6 мм' },
      { key: 'Страна', value: 'Италия' },
    ],
    categorySlug: 'dushevye-kabiny',
    imageUrls: [],
  },
  {
    title: 'Душевой поддон Kaldewei Superplan Plus 90x120',
    slug: 'kaldewei-superplan-plus-90x120',
    price: 31200,
    sku: 'KAL-386147980001',
    inStock: 'preorder',
    rating: { value: r(4.6, 5.0), count: ri(5, 25) },
    specs: [
      { key: 'Бренд', value: 'Kaldewei' },
      { key: 'Тип', value: 'Душевой поддон' },
      { key: 'Размер, мм', value: '900x1200' },
      { key: 'Высота, мм', value: '25' },
      { key: 'Материал', value: 'Эмалированная сталь' },
      { key: 'Страна', value: 'Германия' },
    ],
    categorySlug: 'dushevye-kabiny',
    imageUrls: [],
  },

  // Полотенцесушители
  {
    title: 'Полотенцесушитель водяной Terminus Фокстрот 500x800',
    slug: 'terminus-fokstrot-500x800',
    price: 6800,
    sku: 'TERM-32-20-500-800',
    inStock: 'in_stock',
    rating: { value: r(4.3, 4.8), count: ri(25, 150) },
    specs: [
      { key: 'Бренд', value: 'Terminus' },
      { key: 'Тип', value: 'Водяной' },
      { key: 'Форма', value: 'Лесенка' },
      { key: 'Ширина, мм', value: '500' },
      { key: 'Высота, мм', value: '800' },
      { key: 'Материал', value: 'Нержавеющая сталь' },
      { key: 'Страна', value: 'Россия' },
    ],
    categorySlug: 'polotencesushiteli',
    imageUrls: [],
  },
  {
    title: 'Полотенцесушитель электрический Sunerzha Богема 600x400',
    slug: 'sunerzha-bogema-600x400',
    price: 9500,
    sku: 'SUN-BOG-600400',
    inStock: 'in_stock',
    rating: { value: r(4.1, 4.6), count: ri(10, 60) },
    specs: [
      { key: 'Бренд', value: 'Sunerzha' },
      { key: 'Тип', value: 'Электрический' },
      { key: 'Мощность, Вт', value: '150' },
      { key: 'Ширина, мм', value: '400' },
      { key: 'Высота, мм', value: '600' },
      { key: 'Страна', value: 'Россия' },
    ],
    categorySlug: 'polotencesushiteli',
    imageUrls: [],
  },

  // Мебель для ванной
  {
    title: 'Тумба с раковиной Aquanet Данте 60',
    slug: 'aquanet-dante-60',
    price: 18900,
    sku: 'AQNET-DANTE-60',
    inStock: 'in_stock',
    rating: { value: r(4.2, 4.7), count: ri(15, 80) },
    specs: [
      { key: 'Бренд', value: 'Aquanet' },
      { key: 'Тип', value: 'Тумба с раковиной' },
      { key: 'Ширина, мм', value: '600' },
      { key: 'Глубина, мм', value: '450' },
      { key: 'Материал', value: 'МДФ' },
      { key: 'Цвет', value: 'Белый' },
      { key: 'Страна', value: 'Россия' },
    ],
    categorySlug: 'mebel-dlya-vannoj',
    imageUrls: [],
  },
  {
    title: 'Зеркальный шкаф Dreja Premium 80',
    slug: 'dreja-premium-80',
    price: 12400,
    sku: 'DREJA-PREM-80',
    inStock: 'in_stock',
    rating: { value: r(4.3, 4.8), count: ri(10, 50) },
    specs: [
      { key: 'Бренд', value: 'Dreja' },
      { key: 'Тип', value: 'Зеркальный шкаф' },
      { key: 'Ширина, мм', value: '800' },
      { key: 'Подсветка', value: 'LED' },
      { key: 'Материал', value: 'МДФ' },
      { key: 'Страна', value: 'Россия' },
    ],
    categorySlug: 'mebel-dlya-vannoj',
    imageUrls: [],
  },
  {
    title: 'Пенал Roca Victoria Nord ZRU9302724',
    slug: 'roca-victoria-nord-zru9302724',
    price: 15600,
    sku: 'ROCA-ZRU9302724',
    inStock: 'preorder',
    rating: { value: r(4.4, 4.9), count: ri(8, 35) },
    specs: [
      { key: 'Бренд', value: 'Roca' },
      { key: 'Тип', value: 'Пенал' },
      { key: 'Ширина, мм', value: '300' },
      { key: 'Высота, мм', value: '1500' },
      { key: 'Цвет', value: 'Белый' },
      { key: 'Страна', value: 'Испания' },
    ],
    categorySlug: 'mebel-dlya-vannoj',
    imageUrls: [],
  },

  // Аксессуары для ванной
  {
    title: 'Держатель полотенец Grohe Essentials 40386001',
    slug: 'grohe-essentials-40386001',
    price: 3200,
    sku: 'GR-40386001',
    inStock: 'in_stock',
    rating: { value: r(4.5, 5.0), count: ri(30, 200) },
    specs: [
      { key: 'Бренд', value: 'Grohe' },
      { key: 'Тип', value: 'Двойной' },
      { key: 'Длина, мм', value: '450' },
      { key: 'Покрытие', value: 'Хром' },
      { key: 'Крепление', value: 'Настенное' },
      { key: 'Страна', value: 'Германия' },
    ],
    categorySlug: 'aksessuary-dlya-vannoj',
    imageUrls: [],
  },
  {
    title: 'Дозатор мыла Emco Loft 0521 001 02',
    slug: 'emco-loft-0521-001-02',
    price: 4800,
    sku: 'EMCO-052100102',
    inStock: 'in_stock',
    rating: { value: r(4.2, 4.7), count: ri(10, 50) },
    specs: [
      { key: 'Бренд', value: 'Emco' },
      { key: 'Тип', value: 'Настенный' },
      { key: 'Объём, мл', value: '250' },
      { key: 'Материал', value: 'Стекло, хром' },
      { key: 'Страна', value: 'Германия' },
    ],
    categorySlug: 'aksessuary-dlya-vannoj',
    imageUrls: [],
  },
  {
    title: 'Крючок Bemeta Omega 104106022',
    slug: 'bemeta-omega-104106022',
    price: 1200,
    sku: 'BEM-104106022',
    inStock: 'in_stock',
    rating: { value: r(4.0, 4.5), count: ri(20, 100) },
    specs: [
      { key: 'Бренд', value: 'Bemeta' },
      { key: 'Тип', value: 'Двойной крючок' },
      { key: 'Покрытие', value: 'Хром' },
      { key: 'Крепление', value: 'Настенное' },
      { key: 'Страна', value: 'Чехия' },
    ],
    categorySlug: 'aksessuary-dlya-vannoj',
    imageUrls: [],
  },
]
